name: BlackFlash
main: com.example.blackflash.BlackFlashPlugin
version: 1.3.0
api-version: 1.20
description: Demonstrates the Black Flash axe, Reverse Cursed Technique healing, and Hado #90: Black Coffin.
commands:
  blackflash:
    description: Give yourself the Black Flash Axe.
    usage: /blackflash
  giverct:
    description: Receive the Reverse Cursed Technique focus item.
    usage: /giverct
  givehado90:
    description: Receive the catalyst for Hado #90: Black Coffin.
    usage: /givehado90
