name: BankaiPlugin
main: com.example.blackflash.BlackFlashPlugin
version: 1.0.0
api-version: "1.20"
commands:
  blackflash:
    description: Trigger Black Flash
    usage: /blackflash
  giverct:
    description: Give Reverse Cursed Technique item
    usage: /giverct
  givehado90:
    description: Give Hado 90 item
    usage: /givehado90
  givebankai:
    description: Give the Bankai activation item
    usage: /givebankai
  bankaireset:
    description: Reset Bankai for the executing player
    usage: /bankaireset
  gojoawakening:
    description: Gives the Gojo Awakening item
    usage: /gojoawakening
  gojoreset:
    description: Fully reset Gojo Awakening state for the executing player
    usage: /gojoreset
  givestarrk:
    description: Give Starrk abilities
    usage: /givestarrk
  starrkpets:
    description: Gives the Starrk Pets ability item
    usage: /starrkpets
  ceror:
    description: Gives red Cero Oscuras
    usage: /ceror
  cerob:
    description: Gives blue Cero Oscuras
    usage: /cerob
  cerog:
    description: Gives green Cero Oscuras
    usage: /cerog
  ceroc:
    description: Gives cyan Cero Oscuras
    usage: /ceroc
  starrkstorm:
    description: Gives the Los Lobos Storm item
    usage: /starrkstorm
