name: BlackFlash
main: com.example.blackflash.BlackFlashPlugin
version: 1.2.0
api-version: 1.20
description: Demonstrates the Black Flash axe and the Reverse Cursed Technique healing channel.
commands:
  blackflash:
    description: Give yourself the Black Flash Axe.
    usage: /blackflash
