name: BankaiPlugin
main: com.example.blackflash.BlackFlashPlugin
version: 1.0
api-version: 1.20
description: Full Ichigo Bankai and Getsuga Tenshou demo with additional legacy abilities.
commands:
  blackflash:
    description: Give yourself the Black Flash Axe.
    usage: /blackflash
  giverct:
    description: Receive the Reverse Cursed Technique focus item.
    usage: /giverct
  givehado90:
    description: Receive the catalyst for Hado #90: Black Coffin.
    usage: /givehado90
  givebankai:
    description: Receive the Bankai transformation weapon.
    usage: /givebankai
  bankaireset:
    description: Reset Bankai state immediately.
    usage: /bankaireset
