name: BankaiPlugin
main: com.example.bankai.BankaiPlugin
version: 1.0.0
api-version: "1.20"
commands:
  givebankai:
    description: Give the Bankai activation item.
    usage: /givebankai
  bankaireset:
    description: Reset Bankai for the executing player.
    usage: /bankaireset
