name: BlackFlash
main: com.example.blackflash.BlackFlashPlugin
version: 1.1.0
api-version: 1.20
description: Demonstrates the Black Flash ability with a special golden axe.
commands:
  blackflash:
    description: Gives you the Black Flash Axe.
    usage: /blackflash
